site_name: Tự học khoa học máy tính & lập trình - Khu học mở
site_description: vozer vozer vozer vozer vozer vozer vozer
site_author: khuhocmo
repo_url: https://github.com/daihocmo/khmt-lt
repo_name: Đóng góp trên Github

nav:
  - 'Trang chủ': 
    - 'Trang chủ': 'index.md'
  - 'Cơ bản':
    - 'Bài học vỡ lòng': 'co-ban/bat-dau.md'
    - 'Tư duy lập trình': 'co-ban/tu-duy-lap-trinh.md'
    - 'Ghi nhớ': 'co-ban/ghi-nho.md'
    - 'Nhật ký code': 'co-ban/nhat-ky-code.md'
    - 'Cách lên kế hoạch': 'co-ban/cach-len-ke-hoach.md'
    - 'Cách để đọc Documentation': 'co-ban/cach-doc-docs.md'
    - 'Cách đặt câu hỏi': 'co-ban/cach-dat-cau-hoi.md'
    - 'Làm thật nhiều dự án': 'co-ban/lam-that-nhieu-du-an.md'
    - 'Tìm hiểu thêm': 'co-ban/tim-hieu-them.md'
  - 'Khoa học máy tính':
    - 'Chương trình học': 'khmt/index.md'
  - 'Định hướng':
    - 'Các định hướng chuyên ngành': 'dinh-huong/index.md'
    - 'Mobile':
      - 'Native iOS (Swift)': 
        - 'Định hướng': 'dinh-huong/swift/index.md'  # Adding Swift inside Mobile
        - 'Nền tảng Swift': 'dinh-huong/swift/swift-foundation.md'  
        - 'UIKit': 'dinh-huong/swift/swift-uikit.md'  
        - 'SwiftUI': 'dinh-huong/swift/swift-swiftui.md'
        - 'Swift nâng cao': 'dinh-huong/swift/swift-advance.md'
        - 'Swift Reference': 'dinh-huong/swift/swift-reference.md'
      - 'Native Android (Kotlin)':
        - 'Định hướng': 'dinh-huong/kotlin/index.md'  # Adding Swift inside Mobile
        - 'Nền tảng Kotlin': 'dinh-huong/kotlin/kotlin-foundation.md'
    - 'Web': 
      - 'Fullstack': 'dinh-huong/web/fullstack.md'
      - 'Backend': 'dinh-huong/web/backend.md'
    - 'Game': 
      - 'Chung': 'dinh-huong/game/index.md'
  - 'Ngôn ngữ':
    - 'Rust': 'ngon-ngu/rust.md'
  - 'Tài nguyên':
    - 'Tổng hợp': 'tong-hop.md'

      
theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlighting
    - search.share
  name: material
  icon:
    repo: fontawesome/brands/github
  language: vi
      
plugins:
  - search
  - open-in-new-tab
  
extra:
  generator: false